### ISSUE TITLE
compile bug in crashhandler_win

### ISSUE THREAD

**Issue by cmasiewicz** [KjellKod/g2log#1]
LogEntry entry = {fatal_stream.str(), systemtime_now()}; is missing below:

void crashHandler(int signal_number)
{
    using namespace g2::internal;
    std::ostringstream fatal_stream;
    fatal_stream << "\n\n***** FATAL TRIGGER RECEIVED ******* " << std::endl;
    fatal_stream << "\n***** RETHROWING SIGNAL " << signalName(signal_number) << "(" << signal_number << ")" << std::endl;
	// BUG FIX - CM
	LogEntry entry = {fatal_stream.str(), systemtime_now()};

    FatalMessage fatal_message(entry,FatalMessage::kReasonOS_FATAL_SIGNAL, signal_number);
    FatalTrigger trigger(fatal_message);  std::ostringstream oss;
    std::cerr << fatal_message.message_.msg_ << std::endl << std::flush;
} // scope exit - message sent to LogWorker, wait to die...
} // end anonymous namespace

**Comment by KjellKod** [comment]
g2log is not something I spend time on now. It was merely moved here since BitBucket were scrapping their support for mercurial (it got moved to GitHub and upgraded to use git). 

I recommend you to check out the newer version G3log instead

**Comment by KjellKod** [comment]
No maintenance support for  g2log. See the updates readme
